### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by AlexErrant** [tweag/rust-wasm-threads#7]
As you may know,

> You're under no obligation to choose a license. However, without a license, the default copyright laws apply, meaning that you retain all rights to your source code and no one may reproduce, distribute, or create derivative works from your work.

https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository

[The blog](https://www.tweag.io/blog/2022-11-24-wasm-threads-and-messages) is under CC BY 4.0 DEED, which seems kinda in line with an MIT license? IDK I'm not a lawyer I pretty much hate this kinda stuff - but I kinda need to know the license before I go using it in other OSS projs.

**Comment by jneem** [comment]
Oh, good point. I'm not very opinionated about licenses, so I just went with MIT or Apache 2.0, which seems to be common for rust projects.

**Comment by aspiwack** [comment]
For the record, our default license is MIT. But Apache's fine too.
